name: Reviews

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * 2

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  PUBLIC_ASSET_BRANCH: ${{ secrets.PUBLIC_ASSET_BRANCH }}
  PUBLIC_ASSET_REPO: ${{ secrets.PUBLIC_ASSET_REPO }}
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
  PUBLIC_WARGAMING_APPLICATION_ID: ${{ secrets.PUBLIC_WARGAMING_APPLICATION_ID }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  PUBLIC_ASSET_BASE: ${{ secrets.PUBLIC_ASSET_BASE }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GH_TOKEN }}
      - uses: oven-sh/setup-bun@v1
      - uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GH_TOKEN }}
      - run: bun run setup

      - name: Find reviews
        run: bun run build:reviews
